### ISSUE TITLE
PCB: add sorcing instructions and CPL data

### ISSUE THREAD

**Issue by d1nuc0m** [floookay/adelheid#7]
Ordering a custom PCB might not be easy for someone who is a newbie like me :)
It would be nice to have some recommendations such as layers number (2 if I'm not wrong), thickness (is 1.6 mm ok?), minimum hole size, outer copper weight

Also, some PCB manufacturers also offer assembly of SMD components, but I wasn't able to find CPL data in the Gerber/in the repository, only the BOM. Is it possible to have it?

**Comment by floookay** [comment]
Yes, I can add that. The default values PCB manufactures offer are all fine (2 layers, 1.6mm, etc.). The CPL data is in the other file in the gerber folder: `pcb/adelheid.gerber/adelheid-bottom-pos.csv`  
I don't remember why I didn't call it CPL :sweat_smile:

**Comment by d1nuc0m** [comment]
Thank you, I didn't know how to find it, electronics is not my field
